name: Forwarder Windows

on:
  push:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal
      - run: cargo install cross
      - uses: Swatinem/rust-cache@v2
      - name: Build windows forwarder release
        run: cross build --release --target x86_64-pc-windows-gnu --bin forwarder
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/x86_64-pc-windows-gnu/release/forwarder.exe
